---
# Monitoring Stack Default Variables

# Prometheus
prometheus_version: latest
prometheus_port: 9090
prometheus_data_dir: /var/lib/prometheus
prometheus_config_dir: /etc/prometheus
prometheus_retention_time: 30d
prometheus_retention_size: 50GB
prometheus_scrape_interval: 15s
prometheus_scrape_timeout: 10s
prometheus_evaluation_interval: 15s

# Grafana
grafana_version: latest
grafana_port: 3000
grafana_admin_user: admin
grafana_data_dir: /var/lib/grafana
grafana_config_dir: /etc/grafana
grafana_provisioning_dir: /etc/grafana/provisioning
grafana_dashboards_dir: /var/lib/grafana/dashboards
grafana_logs_dir: /var/log/grafana

# Elasticsearch
elasticsearch_version: 8.0.0
elasticsearch_port: 9200
elasticsearch_cluster_name: yawl-cluster
elasticsearch_data_dir: /var/lib/elasticsearch
elasticsearch_logs_dir: /var/log/elasticsearch
elasticsearch_heap_size: 2g
elasticsearch_discovery_type: single-node
elasticsearch_index_number_of_shards: 1
elasticsearch_index_number_of_replicas: 0
elasticsearch_xpack_security_enabled: false

# Kibana
kibana_version: 8.0.0
kibana_port: 5601
kibana_data_dir: /var/lib/kibana
kibana_logs_dir: /var/log/kibana

# Logstash
logstash_version: 8.0.0
logstash_port: 5000
logstash_config_dir: /etc/logstash
logstash_data_dir: /var/lib/logstash
logstash_logs_dir: /var/log/logstash
logstash_pipeline_workers: 4
logstash_pipeline_batch_size: 125

# Alertmanager
alertmanager_version: latest
alertmanager_port: 9093
alertmanager_config_dir: /etc/alertmanager
alertmanager_data_dir: /var/lib/alertmanager
alertmanager_resolve_timeout: 5m

# Filebeat
filebeat_version: 8.0.0
filebeat_logs_dir: /var/log/filebeat
filebeat_data_dir: /var/lib/filebeat

# General
monitoring_enabled: true
logs_retention_days: 30
metrics_retention_days: 365
