---
# Docker Handlers

- name: restart docker
  systemd:
    name: docker
    state: restarted
  listen: "restart docker"

- name: reload docker
  systemd:
    name: docker
    state: reloaded
  listen: "reload docker"

- name: restart docker containers
  shell: "docker restart $(docker ps -aq)"
  listen: "restart docker containers"
