{{- if .Values.global.namespace -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "yawl.namespace" . }}
  labels:
    {{- include "yawl.labels" . | nindent 4 }}
    app.kubernetes.io/component: namespace
    app.kubernetes.io/version: {{ .Values.yawlVersion | quote }}
  annotations:
    scheduler.alpha.kubernetes.io/defaultTolerations: "[]"
    scheduler.alpha.kubernetes.io/tolerationsWhitelist: "[]"
    {{- with .Values.global.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
