apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-postgresql-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  postgresql.conf: |
{{ .Values.primary.configuration | indent 4 }}
