apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-redis-auth
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  password: {{ .Values.auth.password | quote }}
